POST http://localhost:3000/api/action
Content-Type: application/json

{
  "curlCommand": "curl http://localhost:3000/api/dummy",
  "actionName": "accountUpgrade",
  "description": "upgrade the account"
}

###
GET http://localhost:3000/api/action/accountUpgrade
Content-Type: application/json
Accept: application/json


###
GET http://localhost:3000/api/dummy