### Create action using curl
POST http://localhost:3000/api/actions/curl
Content-Type: application/json

{
  "format": "curl",
  "content": "curl http://localhost:3000/api/upgrade",
  "actionName": "accountUpgrade",
  "description": "upgrade the account"
}

### Create action using OpenAPI spec (YAML)
POST http://localhost:3000/api/actions/openapi
Content-Type: application/json

{
  "format": "openapi",
  "content": "openapi: 3.0.3\ninfo:\n  title: Upgrade API\n  version: 1.0.0\n  description: A simple API for account upgrade operations\nservers:\n  - url: http://localhost:3000\n    description: Local development server\npaths:\n  /api/upgrade:\n    get:\n      operationId: accountUpgrade\n      summary: Upgrade the account\n      description: Initiates an account upgrade process\n      responses:\n        '200':\n          description: Successful response\n          content:\n            application/json:\n              schema:\n                type: object\n                properties:\n                  status:\n                    type: string\n                    example: success\n                  message:\n                    type: string\n                    example: Account upgraded successfully"
}

### Create action using OpenAPI spec (JSON)
POST http://localhost:3000/api/actions/openapi
Content-Type: application/json

{
  "format": "openapi",
  "content": "{\"openapi\":\"3.0.3\",\"info\":{\"title\":\"Upgrade API\",\"version\":\"1.0.0\",\"description\":\"A simple API for account upgrade operations\"},\"servers\":[{\"url\":\"http://localhost:3000\",\"description\":\"Local development server\"}],\"paths\":{\"/api/upgrade\":{\"get\":{\"operationId\":\"accountUpgrade\",\"summary\":\"Upgrade the account\",\"description\":\"Initiates an account upgrade process\",\"responses\":{\"200\":{\"description\":\"Successful response\",\"content\":{\"application/json\":{\"schema\":{\"type\":\"object\",\"properties\":{\"status\":{\"type\":\"string\",\"example\":\"success\"},\"message\":{\"type\":\"string\",\"example\":\"Account upgraded successfully\"}}}}}}}}}}}"
}


### Create action using form
POST http://localhost:3000/api/actions/form
Content-Type: application/json

{
  "name": "Some Action Name",
  "description": "Some Action Description",
  "executionContext": "SERVER",
  "executionModel": {
    "request": {
      "url": "https://api.sampleapis.com/coffee/{{foo}}",
      "method": "GET",
      "headers": {
        "SomeHeader": "SomeHeaderValue",
        "SomeOtherHeader": "{{bar}}"
      },
      "body": {
        "key": "{{baz}}"
      }
    },
    "parameters": [
      {
        "name": "foo",
        "description": "a description for data input foo",
        "type": "text",
        "isArray": false
      },
      {
        "name": "Some Input Bar",
        "description": "a description for data input bar",
        "type": "text",
        "isArray": false
      }
    ]
  }
}

### Get action by name
GET http://localhost:3000/api/actions/accountUpgrade
Content-Type: application/json
Accept: application/json

### Get all actions
GET http://localhost:3000/api/actions
Content-Type: application/json
Accept: application/json
