POST http://localhost:3000/api/documents
Content-Type: application/json

{
  "text": "Chess is a game of skill.",
  "metadata": {
    "source": "test",
    "category": "boardgames",
    "chatbotId": "ae262222-4bea-48fe-a949-345493dfb465"
  }
}

###

POST http://localhost:3000/api/documents
Content-Type: application/json

{
  "text": "The beach is wonderful today.",
  "metadata": {
    "source": "test",
    "category": "vacation",
    "chatbotId": "ae262222-4bea-48fe-a949-345493dfb465"
  }
}

###

POST http://localhost:3000/api/documents/search
Content-Type: application/json

{
  "query": "the waves are great",
  "topK": 3,
  "chatbotId": "ae262222-4bea-48fe-a949-345493dfb465"
}

###

POST http://localhost:3000/api/documents/search
Content-Type: application/json

{
  "query": "checkmate!",
  "topK": 2,
  "chatbotId": "ae262222-4bea-48fe-a949-345493dfb465"
}